import './globals.css'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })
import { SkeletonTheme } from 'react-loading-skeleton';

export const metadata = {
  title: 'Quickie VDDW Search',
  description: 'Generated by create next app and a bare minimum of effort',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SkeletonTheme baseColor="#4400cc" highlightColor="#444">{children}</SkeletonTheme>
      </body>
    </html>
  )
}
